# Generated by Django 4.0.1 on 2022-01-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='testemail123@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
