# Generated by Django 4.0.1 on 2022-03-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_default_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sharedProfiles',
            field=models.ManyToManyField(blank=True, to='users.Profile'),
        ),
    ]
