# Generated by Django 4.0.1 on 2022-01-10 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('entry', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='data.entry')),
            ],
        ),
    ]
