# Generated by Django 4.0.1 on 2022-01-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrytag',
            name='tag',
            field=models.CharField(max_length=20),
        ),
    ]
