# Generated by Django 4.0.1 on 2022-01-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_entrytag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrytag',
            name='entry',
        ),
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(blank=True, to='data.EntryTag'),
        ),
        migrations.AlterField(
            model_name='entrytag',
            name='tag',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
