# Generated by Django 4.0.1 on 2022-01-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_entrytag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
            preserve_default=False,
        ),
    ]
