# Generated by Django 4.0.1 on 2022-01-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_entry_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='notes',
            field=models.TextField(default='Entry Notes', max_length=500),
            preserve_default=False,
        ),
    ]
